<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tsbo4UT' shared service.

return $this->privates['.service_locator.tsbo4UT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'campeonato' => array('privates', '.errored..service_locator.tsbo4UT.App\\Entity\\Campeonato', NULL, 'Cannot autowire service ".service_locator.tsbo4UT": it references class "App\\Entity\\Campeonato" but no such service exists.'),
));
