<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eANm2nL' shared service.

return $this->privates['.service_locator.eANm2nL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'time' => array('privates', '.errored..service_locator.eANm2nL.App\\Entity\\Time', NULL, 'Cannot autowire service ".service_locator.eANm2nL": it references class "App\\Entity\\Time" but no such service exists.'),
));
