<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.eANm2nL.App\Entity\Time' shared service.

include_once $this->targetDirs[3].'/src/Entity/Time.php';

return $this->privates['.errored..service_locator.eANm2nL.App\Entity\Time'] = new \App\Entity\Time();
