<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUohiTSr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUohiTSr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUohiTSr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUohiTSr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUohiTSr\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'UohiTSr',
    'container.build_id' => 'acbdccc4',
    'container.build_time' => 1547055224,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUohiTSr');
