<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxTwIbx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxTwIbx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxTwIbx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxTwIbx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZxTwIbx\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'ZxTwIbx',
    'container.build_id' => '64aa4e47',
    'container.build_time' => 1546956245,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxTwIbx');
